### ISSUE TITLE
Default inference not picking up URL features on Restaurant_Likes.csv

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/woodwork#1347]
#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd
import woodwork as ww

X = pd.read_csv("/Users/freddy.boulton/Downloads/Restaurant_Likes.csv")
X.ww.init()

assert X.ww.schema.columns['Restaurant URL'].logical_type.type_string == 'categorical'
```

```
!pip freeze | grep -E "pandas|woodwork"
```
```
pandas==1.4.0
woodwork==0.14.0
```

![image](https://user-images.githubusercontent.com/41651716/159307341-6e70e5ba-0eba-4d01-84bf-8f7f9d56871e.png)

[Restaurant_Likes.csv](https://github.com/alteryx/woodwork/files/8317278/Restaurant_Likes.csv)

**Comment by thehomebrewnerd** [comment]
I haven't really studied this in detail, but I suspect what is happening here is that Woodwork is identifying that this column could be `Categorical` or it could be `URL`. Because these are both "root" types in Woodwork and exist at the same top-level of the type hierarchy, Woodwork is returning the first valid type it found, which is probably `Categorical`.

Might need to consider making URL a sub-type of Categorical by adding a relationship between the two in the type system, or changing the logic when multiple type matches are found
