### ISSUE TITLE
Type information lost when converting to numpy

### ISSUE THREAD

**Issue by angela97lin** [alteryx/woodwork#456]
When I convert a numeric DataTable to pandas --> to numpy, I expect the resulting numpy array to have a numeric dtype.

```python
import pandas as pd
import numpy as np
import woodwork as ww

y = pd.Series([1, 0, 1, 1])
X = pd.DataFrame()
X["a"] = y * 3
X["b"] = y - 1
X["c"] = y / 10
X["d"] = ~y
X["e"] = [0, 0, 0, 0]
ww.DataTable(X).to_dataframe().to_numpy()
```
Results in
```
array([[3, 0, 0.1, -2, 0],
       [0, -1, 0.0, -1, 0],
       [3, 0, 0.1, -2, 0],
       [3, 0, 0.1, -2, 0]], dtype=object)
```

Even though ```ww.DataTable(X).types``` produces
```
            Physical Type Logical Type Semantic Tag(s)
Data Column
a                   Int64      Integer       {numeric}
b                   Int64      Integer       {numeric}
c                 float64       Double       {numeric}
d                   Int64      Integer       {numeric}
e                   Int64      Integer       {numeric}
```

If I took the original pandas df and called `X.to_numpy()`, I get a numpy array with dtype=float64:
```
array([[ 3. ,  0. ,  0.1, -2. ,  0. ],
       [ 0. , -1. ,  0. , -1. ,  0. ],
       [ 3. ,  0. ,  0.1, -2. ,  0. ],
       [ 3. ,  0. ,  0.1, -2. ,  0. ]])
```

Note: could be related to #455

**Comment by tyler3991** [comment]
@angela97lin what's the status here. Is there still woodwork work to be done to help here?

**Comment by angela97lin** [comment]
No, I'm not sure there's any woodwork work to be done left so I'll close. Thanks @gsheni and @thehomebrewnerd for the workarounds!

**Comment by tyler3991** [comment]
thanks @angela97lin  !!

**Comment by DataSciencemumbai** [comment]
This discrepancy may be due to the way Woodwork handles data types and how they are preserved during conversions.

To ensure that the resulting numpy array has a numeric dtype, you can explicitly convert the DataFrame to a numeric dtype before converting it to a numpy array. Here's how you can do it:
```
import pandas as pd
import numpy as np
import woodwork as ww

y = pd.Series([1, 0, 1, 1])
X = pd.DataFrame()
X["a"] = y * 3
X["b"] = y - 1
X["c"] = y / 10
X["d"] = ~y
X["e"] = [0, 0, 0, 0]

# Convert to Woodwork DataTable
datatable = ww.DataTable(X)

# Convert to pandas DataFrame
df = datatable.to_dataframe()

# Convert DataFrame to numeric dtype
df_numeric = df.apply(pd.to_numeric, errors='ignore')

# Convert DataFrame to numpy array
numpy_array = df_numeric.to_numpy()

print(numpy_array)
```

The output for the provided code snippet would be the resulting numpy array:
```
array([[ 3. ,  0. ,  0.1, -2. ,  0. ],
       [ 0. , -1. ,  0. , -1. ,  0. ],
       [ 3. ,  0. ,  0.1, -2. ,  0. ],
       [ 3. ,  0. ,  0.1, -2. ,  0. ]])
```
This numpy array represents the data from the original DataFrame X, where all values have been converted to numeric dtype.

For more such insightful knowledge do checkout [Data Science Training courses](https://bostoninstituteofanalytics.org/data-science-and-artificial-intelligence/) to kick start your journey in python programming
