### ISSUE TITLE
Init Series Accessor with dictionary of column typing info

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#526]
Similar to how we allow `df.ww.init(schema)`, we want to allow `series.ww.init(col_dict)` when:
- the series' dtype matches the Logical Type's dtype
- The name matches the name of the series

**Comment by thehomebrewnerd** [comment]
Wondering if this needs any special implementation. If the keys in `col_dict` match the keyword arguments for the init function (which they currently do), can't we just call `series.ww.init(**col_dict)` to achieve this functionality?

**Comment by tamargrey** [comment]
@thehomebrewnerd That makes sense to me! (and maybe a point towards sticking with the dictionary implementation??)

**Comment by thehomebrewnerd** [comment]
Closing this issue for now. Since the column schema is currently just a dictionary, we can unpack it and use it to initialize a new series if needed. Note - this does require dropping the `dtype` key-value pair from the dictionary first but other than that requires no special treatment. We can reopen in the future or create a new issue if additional work is required on this.
