### ISSUE TITLE
Add input validation to ww.init_series

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#631]
The `init_series` function added as part of the accessor update does not validate that the input passed in for the series is a valid series type. If the user passes in a non-series object an error is currently raised, but the error message is not helpful in understanding what went wrong.  Current behavior:
```python
>>> ww.init_series(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nate.parsons/dev/woodwork/woodwork/accessor_utils.py", line 38, in init_series
    logical_type = _get_column_logical_type(series, logical_type, series.name)
AttributeError: 'int' object has no attribute 'name'
```

We should add a validation check to this function and raise a better error if improper inputs are supplied.

**Comment by tyler3991** [comment]
It seems like having an error here that makes sense is pretty important. I think it's worth prioritizing. What do you think @thehomebrewnerd, @gsheni ?

**Comment by thehomebrewnerd** [comment]
@tyler3991 I'm fine with working this sooner rather than later. Having a meaningful error would be good, and this should be an easy fix.

**Comment by tamargrey** [comment]
@tyler3991 @gsheni @thehomebrewnerd 

Been thinking about getting to feature parity with DataTables.

I think this issue, #501, and #570 might all be necessary for that unless we say that losing the ability to init Woodwork on numpy arrays and ExtensionArrays is fine for the initial Accessor implementation. I think if we're going to update `init_series` for those two issues, we'd need to also implement this issue, so that's why I'm tying them together here.

**Comment by gsheni** [comment]
@tamargrey Let's push to get the accessor implementation done, and keep the ability to init WW with numpy arrays/Extensions array out of this sprint. 

We have those issues you mentioned (so if EvalML really needs it for their implementation, we can follow up later on).
