### ISSUE TITLE
Latest Dependency Checker not running with pandas 1.2.4

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#811]
- We have the latest dependency that runs every hour. However, pandas 1.2.4 was released 3 hours ago and MR to update latest_dependencies was not put up.
  - https://github.com/alteryx/woodwork/blob/main/woodwork/tests/latest_dependencies.txt#L5
- It is likely that a test req or dev req is restrict the latest pandas from being installed.

**Comment by thehomebrewnerd** [comment]
@gsheni I don't think this is a bug, but not 100% sure. My guess is that this is because Koalas currently has a restriction on the pandas version, so when our dependencies get installed the resolver installs a lower version of pandas. Same likely holds true for Featuretools.

[Related Issue](https://github.com/databricks/koalas/issues/2134)
[Another Related Issue](https://github.com/databricks/koalas/issues/2137)

**Comment by gsheni** [comment]
Closing as Nate is correct and this is because Koalas is restricting the version

**Comment by thehomebrewnerd** [comment]
@gsheni After thinking about this a bit more, I think we might want to make sure we are always testing with latest version of pandas (maybe without the optional dependencies) since pandas is probably the most important dependency we have. Maybe that means another version of the dependency checker?
