### ISSUE TITLE
It's possible to create an invalid schema with ww.init

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/woodwork#846]
It's possible to create an invalid schema by typing a column with pandas dtype `category` and missing values as Boolean in ww 0.2.0.

I would expect `ww.init` to error out letting me know the type I requested is not compatible with my data, just like what happens when you try to go from `Category` to `Double`.

This isn't blocking evalml. Users can catch this with the `is_schema_valid` helper function introduced in https://github.com/alteryx/woodwork/pull/834 but it might be better to check the schema during `ww.init`. 

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd
import woodwork as ww
from woodwork.table_accessor import _get_invalid_schema_message

df = pd.DataFrame(pd.Series(["a", "b", None], dtype='category'))
df.ww.init(logical_types={0: "Boolean"})
assert _get_invalid_schema_message(df, df.ww.schema)
df
```
```
Out[4]:
      0
0  True
1  True
2   NaN
```

**Comment by thehomebrewnerd** [comment]
Woodwork relies on pandas to tell us whether a dtype conversion is valid or not. In this case, pandas is quite happy to allow a conversion of this type:

```python
>>> import pandas as pd
>>> df = pd.DataFrame(pd.Series(["a", "b", None], dtype='category'))
>>> df.astype({0: 'bool'})
      0
0  True
1  True
2  True
```

The pandas behavior is why Woodwork does not identify the data as being incompatible with the specified logical type. We could implement our own custom checks to catch these types of situations, but the downside will be degraded performance during initialization, of course.

**Comment by freddyaboulton** [comment]
@thehomebrewnerd How come in my example, woodwork does not convert the `None` to `True` like pandas `astype` does?

I think the problem is that woodwork is converting `None` to `NaN` which invalidates the schema as soon as the accessor is initialized.

**Comment by thehomebrewnerd** [comment]
@freddyaboulton Ah, I think I read this wrong initially. Let me take another look...

**Comment by thehomebrewnerd** [comment]
The difference in behavior between what I saw and what you saw seems to be a result of us using different pandas versions. I was using 1.1.5 (which is needed for Koalas), but starting in 1.2.0 it seems the behavior of `.astype('bool')` changed. When you run on 1.1.5 you get this:

```python
>>> import pandas as pd
>>> df = pd.DataFrame(pd.Series(["a", "b", None], dtype='category'))
>>> df.astype({0: 'bool'})
      0
0  True
1  True
2  True
>>> df.astype({0: 'bool'})[0].dtype
dtype('bool')
```

But on 1.2.0 you get this:
```python
>>> import pandas as pd
>>> df = pd.DataFrame(pd.Series(["a", "b", None], dtype='category'))
>>> df.astype({0: 'bool'})
      0
0  True
1  True
2   NaN
>>> df.astype({0: 'bool'})[0].dtype
dtype('O')
```

So, in `pandas>=1.2.0`, the type conversion still succeeds, but it gives you an `object` dtype instead of the `bool` dtype that was specified. From a Woodwork perspective this is invalidating our schema because the new column dtype of `object` doesn't match the expected dtype of `bool` for the Boolean logical type. Because pandas is allowing the astype conversion without error (even though it isn't doing what you asked), Woodwork is not catching this problem nor generating an error like it does for other invalid type conversions.

I'm not sure if this is a Woodwork bug or a pandas bug, but in either case, I'll think a bit more about how we might cleanly catch this problem in Woodwork.

**Comment by gsheni** [comment]
Could we put a check statement after the conversion to make sure the new Series dtype matches?

**Comment by thehomebrewnerd** [comment]
> Could we put a check statement after the conversion (in Woodwork) to make sure the new Series dtype matches?

Yeah, I think that should do it, in this case at least.
