### ISSUE TITLE
Ability to concat dataframes through woodwork

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/woodwork#884]
- As a [user/developer], I wish I could use Woodwork to concat multiple dataframes through the woodwork accessor and preserve the schema. Users can currently do this by looping over the columns in a new dataframe and doing `df.ww["col_name"] = col` but it would be much better to avoid having to write the loop each time.

I think we should prioritize concatting along `axis 1`, i.e. adding new columns as opposed to rows. 

#### Code Example

```python
new_dataframe = ww.concat([original_dataframe, new_df])
new_dataframe = ww.concat([original_dataframe, new_df, df_2])
```

The two tricky cases I can imagine right now are dataframes with different primary keys/time indices. I think it's ok to error out if the indices don't match. This might be better than what `pandas.concat` does which is will fill in NaNs where the indices don't overlap I believe.

**Comment by tamargrey** [comment]
@freddyaboulton Trying to get a better idea of what we're looking to build here. I agree we can focus on handling the `axis=1` case as a first step, but in order to figure out the best way to handle index conflicts, I think we need to answer another question first:

Are you imagining that the operation here would just combine all sets of columns from the different tables (pd.concat) or merge them if there's overlap between the names (DataFrame.merge, I believe)?

`pd.concat` will not combine duplicate column names from what I can tell, and this is a problem for Woodwork where we require unique column names. However, in order to have matching underlying indexes if there's a Woodwork index set, there will need to be corresponding columns in the DataFrame. So I'm wondering if what we're looking for is an "outer" `DataFrame.merge` here? 

![image.png](https://images.zenhubusercontent.com/5f15e80b8f74aa3e95d9e419/3aea7301-a0f5-47fa-b83e-9a3dc0877e65)

**Comment by freddyaboulton** [comment]
@tamargrey Thanks for getting back to me! My primary use case is adding columns to an existing dataframe. I think it'd be best if `ww.concat` behaves as similarly as `pd.concat` as possible. To make sure I understand - your plan is to use `pd.concat` when at most one df has an index, else merge when they have matching index columns? 

Just to throw out another idea - I wonder if we can just retain the index of the first dataframe and concat like `pd.concat` does?
