### ISSUE TITLE
Smart datetime inference

### ISSUE THREAD

**Issue by dsherry** [alteryx/woodwork#898]
**Problem**
Suppose I have three string columns in my inputted data, with values matching these three formats, in order:
1. 2021-05-06 14:00:00 EDT
2. 2:00 pm May 6th, 2020
3. 05/06/2021 14:00

Since none of those conform exactly to ISO timestamp format, woodwork currently can't detect that these are datetime features, and will set all three of those columns as either categorical or natural language.

**Feature Request**
I'd like woodwork's inference to be able to tell that these are datetime-type columns, to infer the expected datetime parse format for each column and to also validate that all the data conform to that format.

**Challenges**
* Truncated formats. 05/06/21 and 05/06/2021 could resolve to the same date or could be 2000 years apart.
* Speed. Ideally the inference step could work without having to examine every value in the column. Then validation could check all the values.

One thing which could help: we could define a list of common datetime parse strings.
Another: a feature which got the right answer 90% of the time, and allowed users to correct for the other 10%, would be incredibly valuable in my opinion; doesn't need to be perfect.

Original discussion in https://github.com/alteryx/evalml/issues/2134

**Comment by thehomebrewnerd** [comment]
@dsherry Can you please provide an example where you are getting behavior you don't expect from the inference. When I try with all three of these values, Woodwork identifies them as `Datetime` columns:

```python
import pandas as pd
import woodwork as ww

df = pd.DataFrame({
    'idx': [0],
    'date1': ['2021-05-06 14:00:00 EDT'],
    'date2': ['2:00 pm May 6th, 2020'],
    'date3': ['05/06/2021 14:00'],
})

df.ww.init()
df.ww
```

Output:
```
         Physical Type Logical Type Semantic Tag(s)
Column                                             
idx              int64      Integer     ['numeric']
date1   datetime64[ns]     Datetime              []
date2   datetime64[ns]     Datetime              []
date3   datetime64[ns]     Datetime              []
```

I do get a warning associated with the first date related to the timezone, but it is still identified as expected.

**Comment by kmax12** [comment]
can we also then get out the datetime format that was inferred? Because datetime formats are ambiguous, different samples of the data might get inferred differently

the use case I'm thinking of: I loaded training data into woodward and a datetime column was inferred. Then I want to loading in some new data for predicting on and I want to ensure it gets parsed in the same way as the training data.  when i load in the new data, i want it to get parsed exactly the same as the previous data

**Comment by thehomebrewnerd** [comment]
Currently if a user is passing in datetime objects that have an ambiguous format, the best option would be for them to create an instance of the Datetime logical type, specifying the proper format string, and not allowing Woodwork/pandas to infer the format like this:
```
>>> dates = pd.Series(['30/05/2021', '01/05/2021'])
>>> dt_formatted = ww.logical_types.Datetime(datetime_format="%d/%m/%Y")
>>> ww_dates = ww.init_series(dates, logical_type=dt_formatted)
>>> ww_dates
0   2021-05-30
1   2021-05-01
dtype: datetime64[ns]
>>> ww_dates.ww
<Series: None (Physical Type = datetime64[ns]) (Logical Type = Datetime) (Semantic Tags = set())>
```

With this approach, you will at least be guaranteed consistent parsing and conversion.

If we want this type of behavior during inference, we will need to reconfigure how things are done for datetimes, so we can store the format used. It might involve something like @dsherry suggested - storing a list of format strings that we use during inference instead of relying on pandas to infer the format. That still wouldn't prevent us from inferring the format incorrectly, but at least we would have a record of the format that was inferred, so that it could be applied to new data.

**Comment by kmax12** [comment]
that behavior you describe where it treats each element is different is weird based on my reading of [the code](https://github.com/pandas-dev/pandas/blob/v1.2.4/pandas/core/tools/datetimes.py#L80) because it appears to look at just the first element...

i'd be curious to understand that behavior a bit more, but beyond that I wonder if the solution could be for use to use the `_guess_datetime_format_for_array` or `guess_datetime_format` method to figure out the format and then make a call to `to_datetime` where we explicitly set the format.

I like this approach because the we can expose datetime inference on its (useful for other applications) and we can swap out our technique for inferring datetimes in the future

**Comment by gsheni** [comment]
@kmax12 @dsherry We added functionality to guess the datetime format, and save it on the Datetime Logical Type
- https://github.com/alteryx/woodwork/pull/1025
This was pushed out in the Woodwork v0.5.1 release

**Comment by gsheni** [comment]
Closing as all concerns raised by @dsherry and @kmax12 have been addressed.
