### ISSUE TITLE
set(ww.DataColumn)

### ISSUE THREAD

**Issue by chukarsten** [alteryx/woodwork#908]
- As a developer, I wish I could use easily convert Woodwork DataColumns to sets using the python set constructor. I personally do set(y) frequently to determine how many unique values there are in a list of target values.

#### Code Example

```python
from woodwork import DataColumn

dc = DataColumn([1,2,3,2,1])
dc_set = set(dc)
assert dc_set == {1,2,3}
```

With the current impl, DataColumns return `*** TypeError: 'DataColumn' object is not iterable`.

**Comment by thehomebrewnerd** [comment]
@chukarsten With the new accessor implementation (starting in WW version 0.1.0) there is no more `DataColumn` object. I don't think this will be an issue any more with the series accessor since you would just call `set` on the pandas series object and not a Woodwork object, but please correct me if I'm wrong:

```python
>>> import woodwork as ww
>>> series = pd.Series([1, 2, 3])
>>> series.ww.init()
>>> set(series)
{1, 2, 3}
```

**Comment by gsheni** [comment]
Closing as Series allows for the set call
