### ISSUE TITLE
Add Infer Email Address function

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#945]
- As a user, I wish I could use Woodwork to automatically infer if a column is an Email Address Logical Type (if the majority of the not-NaN values are email address)
- We can use this regex, which captures the majority of situations
  - https://emailregex.com/
- We should sample with 10K rows (first 10K rows, dropna)

#### Code Example

```python
import pandas as pd
import numpy as np
  
data = pd.Series(['fl@alteryx.com', 'bad@email.com', 'no_email', np.nan])

data.str.match(pat=r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
```
```
Out[2]:
0     True
1     True
2    False
3      NaN
dtype: object

```

**Comment by davesque** [comment]
@gsheni Got some questions/comments relating to this ticket and also specifically about the ticket.

### General comments

I've noticed that some of the logic in woodwork that uses the Pandas API is also designed to accommodate Koalas or Dask objects.  For example, this utility func used by the datetime inferer:
https://github.com/alteryx/woodwork/blob/0d5c5c1ff160d35e6c50232ba0184fec860a8343/woodwork/type_sys/utils.py#L12-L35

There's an issue with the code on these lines which might exist in other places as well:
https://github.com/alteryx/woodwork/blob/0d5c5c1ff160d35e6c50232ba0184fec860a8343/woodwork/type_sys/utils.py#L15-L16

The problem is that a partitioned data set (as would be seen with Dask or Koalas) might be way too large to fit into the memory of whatever process is driving a pipeline.  So doing the `.to_pandas()` call might cause the python interpreter (or Kubernetes pod) to get OOM killed.

### About this ticket

Relating more specifically to this ticket, neither Dask nor Koalas support doing a record count sample.  This is because getting a balanced number of records from each partition requires knowing the overall record count.  That requires evaluating the entire data set.  So the record count sample cannot be done in a single pass.  Both Dask and Koalas recommend doing fractional samples instead.  But, in the general case, we can't assume that a data set will be small enough to hard code some constant fraction to look at.

Wouldn't mind doing a bit of rubber ducking on this one.  I think there are different things we could do.  For example, we could just break down and calculate a record count (evaluate all partitions) to determine a fraction that gives a reasonable number of records for a data set.  But, since we're already evaluating the entire data set, it's reasonable to ask whether or not applying the regex to each record wouldn't be just as fast.  In either of those cases, we'd be saying that type inference in a distributed context is a relatively slow operation.  We could also look only at the first partition but the first partition could technically be empty.

I can also just punt on these questions relating to distributed computing and do something like what's already being done in the datetime inference example above.  Thoughts on this one?  Would also love to hear other people's input who have an opinion about this.

**Comment by thehomebrewnerd** [comment]
@davesque Here are a few of my thoughts...

I think the points you raise about how we do inference with Dask and Koalas datasets is valid and something we need to address. In Featuretools, when we added support for Dask and Koalas, we forced the user to supply types for all of their columns and didn't even attempt inference for many of the reasons you highlight. In any case, I think the refactoring for better handling of Dask/Koalas inference in Woodwork should be done in a PR separate from this one. With that in mind, I would recommend that you create a new issue in the Woodwork repo to capture your suggestions and then we can prioritize that appropriately.

Related to the issue of adding an inference function for inferring an email address, you should not need to worry about special handling for Dask or Koalas. In our current inference process, we are always passing a pandas series to the inference function based on this code in `TypeSystem.infer_logical_type`: https://github.com/alteryx/woodwork/blob/0d5c5c1ff160d35e6c50232ba0184fec860a8343/woodwork/type_sys/type_system.py#L258-L262

As this point, the inference function you implement will need to work only for pandas inputs.

Note (`col_is_datetime`) is a bit of a special case as it is also used outside of the inference process and that's why it needs the `to_pandas` calls.

**Comment by davesque** [comment]
Great, thanks for your thoughts there @thehomebrewnerd !

I went ahead and made #1045 as a tracking issue.  I'll just assume Pandas objects for this issue.
